### ISSUE TITLE
Virtual Devices state transitions are not working with zetta 0.20.0 version

### ISSUE THREAD

**Issue by anil614sagar** [zettajs/zetta#152]
App crashes with following errors on state change .. Works with 0.19.0 zetta version..

TypeError: Cannot call method 'publish' of null
    at ObjectStream._write (/Users/anilsagar/Documents/Projects/zetta/contributions/zetta-explorer/node_modules/zetta-car-mock-driver/node_modules/zetta-device/node_modules/zetta-streams/object_stream.js:14:16)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Writable.write (_stream_writable.js:183:11)
    at Object.defineProperty.set (/Users/anilsagar/Documents/Projects/zetta/contributions/zetta-explorer/node_modules/zetta-car-mock-driver/node_modules/zetta-device/device.js:50:21)
    at CAR.startCar (/Users/anilsagar/Documents/Projects/zetta/contributions/zetta-explorer/node_modules/zetta-car-mock-driver/index.js:31:14)
    at Device.call (/Users/anilsagar/Documents/Projects/zetta/contributions/zetta-explorer/node_modules/zetta-car-mock-driver/node_modules/zetta-device/device.js:139:39)
    at run (/Users/anilsagar/Documents/Projects/zetta/contributions/zetta-explorer/node_modules/zetta/lib/api_resources/servers.js:204:17)
    at /Users/anilsagar/Documents/Projects/zetta/contributions/zetta-explorer/node_modules/zetta/lib/api_resources/servers.js:160:12
    at IncomingMessage.<anonymous> (/Users/anilsagar/Documents/Projects/zetta/contributions/zetta-explorer/node_modules/zetta/node_modules/argo/argo.js:100:7)
17 Feb 19:40:33 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by mdobson** [comment]
Hey @anil614sagar Thanks for the bug report. Have potential steps to reproduce? Or code that we can use to reproduce?

**Comment by anil614sagar** [comment]
Hi @mdobson ,

Here are the steps.

1. Add  zetta-led-mock-driver
2. Try to change state of led from off to on using zetta-browser
3. App Crashes

var zetta = require('zetta');
var led = require('zetta-led-mock-driver');

zetta()
.name('Anil Sagar')
.use(led)
.listen(1337, function(){
  console.log('Zetta is running at http://127.0.0.1:1337');
});

**Comment by AdamMagaluk** [comment]
Was able to reproduce and find the issue: PR for the fix is here https://github.com/zettajs/zetta/pull/153

To get around this until a new zetta release is out you can use.



```js
....
var AutoScout = require('zetta-auto-scout');

zetta()
.name('Anil Sagar')
.use(AutoScout 'led', led)
.listen(1337, function(){
  console.log('Zetta is running at http://127.0.0.1:1337');
});
```

**Comment by anil614sagar** [comment]
Thank you @AdamMagaluk .. Above fix is working as expected.

**Comment by AdamMagaluk** [comment]
Closing this issue, zetta@0.21.0 has been released.
