### ISSUE TITLE
Error: socket hang up.

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/zetta#226]
This seems to happen we are testing connections to hubs using 2g wireless.

```
2015-08-18T18:43:47.311734+00:00 app[web.1]: /app/node_modules/zetta/node_modules/titan/node_modules/argo-resource/node_modules/pipeworks/pipeworks.js:200
2015-08-18T18:43:47.311967+00:00 app[web.1]:       throw err; // rethrow
2015-08-18T18:43:47.311984+00:00 app[web.1]:             ^
2015-08-18T18:43:47.313130+00:00 app[web.1]: Error: socket hang up
2015-08-18T18:43:47.313132+00:00 app[web.1]:     at createHangUpError (http.js:1473:15)
2015-08-18T18:43:47.313133+00:00 app[web.1]:     at Stream.socketCloseListener (http.js:1523:23)
2015-08-18T18:43:47.313134+00:00 app[web.1]:     at Stream.emit (events.js:117:20)
2015-08-18T18:43:47.313136+00:00 app[web.1]:     at Object._onImmediate (/app/node_modules/zetta/node_modules/spdy/lib/spdy/stream.js:450:12)
2015-08-18T18:43:47.313137+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:363:15)
```

**Comment by AdamMagaluk** [comment]
Steps to reproduce:

1. Peer a zetta server to the cloud.
2. Make a request to the http://cloud/servers/hub
3. Before the request finishes, disconnect the hub.

In general this is can be hard to replicate on localhost, to verify i added a `setTimeout` with 5000ms to this line. https://github.com/zettajs/zetta/blob/master/lib/api_resources/servers.js#L226

Pretty simple fix, just have to add an `error` handler on this [request object](https://github.com/zettajs/zetta/blob/master/lib/http_server.js#L416), though there may be other places we're not handling req's error events as well.

Currently working on scripted test we can add to our test suite.
