### ISSUE TITLE
Recover from corrupted database

### ISSUE THREAD

**Issue by AdamMagaluk** [zettajs/zetta#246]
The medea dbs can be corrupted, how should zetta handle this. Currently it just throws.

Example error:
```
fs.js:533
  binding.read(fd, buffer, offset, length, position, req);
          ^
Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:533:11)
    at Medea.get (/data/run/v0.1.0_1/node_modules/zetta/node_modules/medea/medea.js:537:6)
    at MedeaIterator._next (/data/run/v0.1.0_1/node_modules/zetta/node_modules/medeadown/medeaiterator.js:28:11)
    at AbstractIterator.next (/data/run/v0.1.0_1/node_modules/zetta/node_modules/medeadown/node_modules/abstract-leveldown/abstract-iterator.js:22:17)
    at ReadStream.read [as _read] (/data/run/v0.1.0_1/node_modules/zetta/node_modules/levelup/lib/read-stream.js:81:18)
    at ReadStream.Readable.read (/data/run/v0.1.0_1/node_modules/zetta/node_modules/levelup/node_modules/readable-stream/lib/_stream_readable.js:362:10)
    at ReadStream.<anonymous> (/data/run/v0.1.0_1/node_modules/zetta/node_modules/levelup/node_modules/readable-stream/lib/_stream_readable.js:785:45)
    at ReadStream.emit (events.js:104:17)
    at emitDataEvents (/data/run/v0.1.0_1/node_modules/zetta/node_modules/levelup/node_modules/readable-stream/lib/_stream_readable.js:811:10)
```

**Comment by kevinswiber** [comment]
This was fixed in medea@1.0.1.  An `npm update` or a new `npm install zetta` should do the trick.
