### ISSUE TITLE
EventSocket Exception on Stream Enabled "null" Value

### ISSUE THREAD

**Issue by wooliet** [zettajs/zetta#328]
_zetta/lib/event_socket.js_
```
EventSocket.prototype.send = function(topic, data) {
  if (!Buffer.isBuffer(data) && typeof data === 'object') {
    var tmpData = (this.streamEnabled) ? data.data : data;

    if (tmpData['transitions']) {
```
**Error: "Cannot read property 'transitions' of null"**

I have a monitorable property "delay" that is typically a decrementing number. It can be set to `null` though, and when it does, the above exception occurs (while events socket is open).

**Comment by wooliet** [comment]
```
TypeError: Cannot read property 'transitions' of null
    at EventSocket.send (/Users/williamking/Projects/Jilia/TOT/tot-sandbox/node_modules/zetta/lib/event_socket.js:190:16)
    at EventBroker._publishStreamEnabledClient (/Users/williamking/Projects/Jilia/TOT/tot-sandbox/node_modules/zetta/lib/event_broker.js:208:10)
    at /Users/williamking/Projects/Jilia/TOT/tot-sandbox/node_modules/zetta/lib/event_broker.js:284:16
    at EventBroker._subscribe.handler (/Users/williamking/Projects/Jilia/TOT/tot-sandbox/node_modules/zetta/lib/event_broker.js:106:5)
    at PubSub._onCallback (/Users/williamking/Projects/Jilia/TOT/tot-sandbox/node_modules/zetta/lib/pubsub_service.js:102:3)
    at EventEmitter.PubSub.subscribe.f (/Users/williamking/Projects/Jilia/TOT/tot-sandbox/node_modules/zetta/lib/pubsub_service.js:44:14)
    at EventEmitter.emit (events.js:129:20)
    at PubSub.publish (/Users/williamking/Projects/Jilia/TOT/tot-sandbox/node_modules/zetta/lib/pubsub_service.js:32:16)
    at ObjectStream._write (/Users/williamking/Projects/Jilia/TOT/stratus-security-service/node_modules/zetta-device/node_modules/zetta-streams/object_stream.js:16:18)
    at doWrite (_stream_writable.js:301:12)
```

**Comment by wooliet** [comment]
```
TypeError: Cannot read property 'transitions' of null
    at EventSocket.send (/Users/me/Projects/zettaproj/node_modules/zetta/lib/event_socket.js:190:16)
    at EventBroker._publishStreamEnabledClient (/Users/me/Projects/zettaproj/node_modules/zetta/lib/event_broker.js:208:10)
    at /Users/me/Projects/zettaproj/node_modules/zetta/lib/event_broker.js:284:16
    at EventBroker._subscribe.handler (/Users/me/Projects/zettaproj/node_modules/zetta/lib/event_broker.js:106:5)
    at PubSub._onCallback (/Users/me/Projects/zettaproj/node_modules/zetta/lib/pubsub_service.js:102:3)
    at EventEmitter.PubSub.subscribe.f (/Users/me/Projects/zettaproj/node_modules/zetta/lib/pubsub_service.js:44:14)
    at EventEmitter.emit (events.js:129:20)
    at PubSub.publish (/Users/me/Projects/zettaproj/node_modules/zetta/lib/pubsub_service.js:32:16)
    at ObjectStream._write (/Users/me/Projects/zettaproj/service/node_modules/zetta-device/node_modules/zetta-streams/object_stream.js:16:18)
    at doWrite (_stream_writable.js:301:12)
```

**Comment by AdamMagaluk** [comment]
Thanks @wooliet i found the error and should have a fix by end of day.

What do you expect the client to see when the value goes `null`?

**Comment by wooliet** [comment]
`null` I suppose. Is that not an expected use case?

**Comment by AdamMagaluk** [comment]
I've published a pre release with this fix in it. You can install it with `zetta@1.3.3-rc.1`
