### ISSUE TITLE
Test failing on windows

### ISSUE THREAD

**Issue by marvinroger** [zettajs/zetta#345]
There's another issue with URLs on Windows. When launched, the output is as follows:

```json
{"class":["root"],"links":[{"rel":["self"],"href":"http://127.0.0.1:1337\\"},{"title":"Test","rel":["http://rels.zettajs.io/server"],"href":"http://127.0.0.1:1337/servers/Test"},{"rel":["http://rels.zettajs.io/events"],"href":"ws://127.0.0.1:1337/events"},{"rel":["http://rels.zettajs.io/peer-management"],"href":"http://127.0.0.1:1337/peer-management"}],"actions":[{"name":"query-devices","method":"GET","href":"http://127.0.0.1:1337\\","type":"application/x-www-form-urlencoded","fields":[{"name":"server","type":"text"},{"name":"ql","type":"text"}]}]}
```

Notice the `http://127.0.0.1:1337\\` instead of `http://127.0.0.1:1337/`.

This causes the following test to fail:

```js
Zetta Api updates href hosts using x-forwarded-host header:
     AssertionError: 'http://google.com\\' == 'http://google.com/'
      at C:\Users\Marvin\Documents\Code\zetta\test\test_api.js:99:22
      at C:\Users\Marvin\Documents\Code\zetta\test\test_api.js:32:5
      at Test.assert (C:\Users\Marvin\Documents\Code\zetta\node_modules\supertest\lib\test.js:213:13)
      at Server.assert (C:\Users\Marvin\Documents\Code\zetta\node_modules\supertest\lib\test.js:132:12)
      at Object.onceWrapper (events.js:293:19)
      at emitNone (events.js:86:13)
      at Server.emit (events.js:188:7)
      at emitCloseNT (net.js:1546:8)
      at _combinedTickCallback (internal/process/next_tick.js:77:11)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

I haven't been able to find the place where the URL helper is defined... But a simple `.replace(/\\/g, '/')` would do.

**Comment by AdamMagaluk** [comment]
We need to upgrade https://github.com/argo/argo-url-helper to the latest as it's fixed in there.

**Comment by marvinroger** [comment]
Actually no, the `titan` package use the `>=0.5.0` version so it uses the latest `argo-url-helper`. There's still a bug affecting the package, I've submitted a PR: https://github.com/argo/argo-url-helper/pull/6

**Comment by kevinswiber** [comment]
@marvinroger This has been merged and published.  Try running `npm --depth 2 update`.

```
🐻  cat node_modules/argo-url-helper/package.json | json version
0.6.0
🐻  npm --depth 2 update                                        
/private/tmp/zetta-play
└─┬ zetta@1.4.0
  └─┬ titan@1.2.0
    └── argo-url-helper@0.7.0 
🐻  cat node_modules/argo-url-helper/package.json | json version
0.7.0
```

Please re-open if you still see an issue.
