### ISSUE TITLE
Project is Broken

### ISSUE THREAD

**Issue by lsntech** [zettajs/zetta#368]
Looks that somebody broken this project, im trying to run it and getting this error:

PS L:\projetos\zozo> node app.js
util.js:291
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:291:11)
    at Object.<anonymous> (L:\projetos\zozo\node_modules\spdy\lib\spdy\connection.js:86:6)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (L:\projetos\zozo\node_modules\spdy\lib\spdy.js:20:19)

trying to run this code from tutorial:

var zetta = require('zetta');

zetta()
  .name('FirstName LastName')
  .listen(1337, function(){
     console.log('Zetta is running at http://127.0.0.1:1337');
});

**Comment by AdamMagaluk** [comment]
There may be issues with compatibility with the latest versions of Node.js. Supported up to v6 for now.

Which version of Node.js are you running?

**Comment by lsntech** [comment]
Hi, 
Node: v11.1.0
Npm: 6.4.1

**Comment by sealedair-elliott** [comment]
@lsntech workaround is to add this before requiring zetta:

```
process.EventEmitter = require('events').EventEmitter; // add this line
const zetta = require('zetta');
```

**Comment by geekdk** [comment]
@sealedair-elliott Thanks for your update, It did work for me.

**Comment by wind13** [comment]
Should update the document then.

**Comment by AdamMagaluk** [comment]
Opened a new PR since i lost access to the repo after leaving Google. https://github.com/zettajs/zetta/pull/379

I also published version zetta@1.6.0 that incorporates all these changes. The latest version of Zetta should work with Node.js 18 and  other newer versions of Node.
